language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "c5efaedd4e39b4584fd4248c9a6d464bc98dc143"
    - GIT_COMMITTER_NAME=rs-ohno-tomoyuki
    - GIT_COMMITTER_EMAIL=ohno.tomoyuki@ricksoft.jp
    - GIT_AUTHOR_NAME=rs-ohno-tomoyuki
    - GIT_AUTHOR_EMAIL=ohno.tomoyuki@ricksoft.jp

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always